#ifndef HIP_INCLUDE_DEVICELIB_SP_INTRINSICS_H
#define HIP_INCLUDE_DEVICELIB_SP_INTRINSICS_H

#include <hip/devicelib/macros.hh>

// __device__​ float __cosf ( float  x )
// __device__​ float __exp10f ( float  x )
// __device__​ float __expf ( float  x )
// __device__​ float __fadd_rd ( float  x, float  y )
// __device__​ float __fadd_rn ( float  x, float  y )
// __device__​ float __fadd_ru ( float  x, float  y )
// __device__​ float __fadd_rz ( float  x, float  y )
// __device__​ float __fdiv_rd ( float  x, float  y )
// __device__​ float __fdiv_rn ( float  x, float  y )
// __device__​ float __fdiv_ru ( float  x, float  y )
// __device__​ float __fdiv_rz ( float  x, float  y )
// __device__​ float __fdividef ( float  x, float  y )
// __device__​ float __fmaf_ieee_rd ( float  x, float  y, float  z )
// __device__​ float __fmaf_ieee_rn ( float  x, float  y, float  z )
// __device__​ float __fmaf_ieee_ru ( float  x, float  y, float  z )
// __device__​ float __fmaf_ieee_rz ( float  x, float  y, float  z )
// __device__​ float __fmaf_rd ( float  x, float  y, float  z )
// __device__​ float __fmaf_rn ( float  x, float  y, float  z )
// __device__​ float __fmaf_ru ( float  x, float  y, float  z )
// __device__​ float __fmaf_rz ( float  x, float  y, float  z )
// __device__​ float __fmul_rd ( float  x, float  y )
// __device__​ float __fmul_rn ( float  x, float  y )
// __device__​ float __fmul_ru ( float  x, float  y )
// __device__​ float __fmul_rz ( float  x, float  y )
// __device__​ float __frcp_rd ( float  x )
// __device__​ float __frcp_rn ( float  x )
// __device__​ float __frcp_ru ( float  x )
// __device__​ float __frcp_rz ( float  x )
// __device__​ float __frsqrt_rn ( float  x )
// __device__​ float __fsqrt_rd ( float  x )
// __device__​ float __fsqrt_rn ( float  x )
// __device__​ float __fsqrt_ru ( float  x )
// __device__​ float __fsqrt_rz ( float  x )
// __device__​ float __fsub_rd ( float  x, float  y )
// __device__​ float __fsub_rn ( float  x, float  y )
// __device__​ float __fsub_ru ( float  x, float  y )
// __device__​ float __fsub_rz ( float  x, float  y )
// __device__​ float __log10f ( float  x )
// __device__​ float __log2f ( float  x )
// __device__​ float __logf ( float  x )
// __device__​ float __powf ( float  x, float  y )
// __device__​ float __saturatef ( float  x )
// __device__​ void __sincosf ( float  x, float* sptr, float* cptr )
// __device__​ float __sinf ( float  x )
// __device__​ float __tanf ( float  x )

#endif // include guard