#ifndef HIP_INCLUDE_MATHLIB_INT_MATH_H
#define HIP_INCLUDE_MATHLIB_INT_MATH_H

#include <hip/mathlib/macros.hh>

// __device__ int abs ( int  a )
// __device__ long int labs ( long int  a )
// __device__ long long int 	llabs ( long long int a )
// __device__ long long int 	llmax ( const long long int a, const long long int b )
// __device__ long long int 	llmin ( const long long int a, const long long int b )
// __device__ unsigned long long int 	max ( const unsigned long long int a, const long long int b )
// __device__ unsigned long long int 	max ( const long long int a, const unsigned long long int b )
// __device__ unsigned long long int 	max ( const unsigned long long int a, const unsigned long long int b )
// __device__ long long int 	max ( const long long int a, const long long int b )
// __device__ unsigned long int 	max ( const unsigned long int a, const long int  b )
// __device__ unsigned long int 	max ( const long int  a, const unsigned long int b )
// __device__ unsigned long int 	max ( const unsigned long int a, const unsigned long int b )
// __device__ long int max ( const long int  a, const long int  b )
// __device__ unsigned int 	max ( const unsigned int  a, const int  b )
// __device__ unsigned int 	max ( const int  a, const unsigned int  b )
// __device__ unsigned int 	max ( const unsigned int  a, const unsigned int  b )
// __device__ int max ( const int  a, const int  b )
// __device__ unsigned long long int 	min ( const unsigned long long int a, const long long int b )
// __device__ unsigned long long int 	min ( const long long int a, const unsigned long long int b )
// __device__ unsigned long long int 	min ( const unsigned long long int a, const unsigned long long int b )
// __device__ long long int 	min ( const long long int a, const long long int b )
// __device__ unsigned long int 	min ( const unsigned long int a, const long int  b )
// __device__ unsigned long int 	min ( const long int  a, const unsigned long int b )
// __device__ unsigned long int 	min ( const unsigned long int a, const unsigned long int b )
// __device__ long int min ( const long int  a, const long int  b )
// __device__ unsigned int 	min ( const unsigned int  a, const int  b )
// __device__ unsigned int 	min ( const int  a, const unsigned int  b )
// __device__ unsigned int 	min ( const unsigned int  a, const unsigned int  b )
// __device__ int min ( const int  a, const int  b )
// __device__ unsigned long long int 	ullmax ( const unsigned long long int a, const unsigned long long int b )
// __device__ unsigned long long int 	ullmin ( const unsigned long long int a, const unsigned long long int b )
// __device__ unsigned int 	umax ( const unsigned int  a, const unsigned int  b )
// __device__ unsigned int 	umin ( const unsigned int  a, const unsigned int  b )

#endif // include guard