// Stub header — redirects CUDA CUB includes to hipCUB equivalents.
// Generated by chipStar for rocThrust CUDA compatibility layer.
#ifndef CHIPSTAR_STUB_CUB_AGENT_SINGLE_PASS_SCAN_OPERATORS_CUH
#define CHIPSTAR_STUB_CUB_AGENT_SINGLE_PASS_SCAN_OPERATORS_CUH
// hipCUB provides the actual implementation via rocPRIM.
// This stub exists so that CUDA Thrust compatibility headers
// (installed by rocThrust) can be included without errors.
#endif
