name: 'Get SHAs'
description: 'Get SHAs of tips of branches we use.'
inputs:
  llvm-version:
    description: 'LLVM version'
    required: true
  pocl-version:
    description: 'pocl version'
    required: false
outputs:
  llvm-sha:
    description: 'SHA of llvm-projetc to checkout'
    value: ${{ steps.llvm-sha.outputs.sha }}
  spirv-llvm-sha:
    description: 'SHA of SIPRV LLVM Translator to checkout'
    value: ${{ steps.spirv-llvm-sha.outputs.sha }}
  pocl-sha:
    description: 'SHA of pocl to checkout'
    value: ${{ steps.pocl-sha.outputs.sha }}
  llvm-cache-key:
    description: 'Key to use when caching LLVM builds'
    value: ${{ runner.os }}-build-cache-llvm-${{ inputs.llvm-version }}-${{ steps.llvm-sha.outputs.sha }}-${{ steps.spirv-llvm-sha.outputs.sha }}
  pocl-cache-key:
    description: 'Key to use when caching pocl builds'
    value: ${{ runner.os }}-build-cache-pocl-${{ inputs.pocl-version }}-llvm-${{ inputs.llvm-version }}-${{steps.pocl-sha.outputs.sha}}-${{ steps.llvm-sha.outputs.sha }}-${{ steps.spirv-llvm-sha.outputs.sha }}
runs:
  using: "composite"
  steps:
    - id: llvm-sha
      run: scripts/get_sha.sh >> $GITHUB_OUTPUT
      env:
        URL: https://api.github.com/repos/CHIP-SPV/llvm-project/git/ref/heads/chipStar-llvm-${{ inputs.llvm-version }}
        TOKEN: u:${{github.token}}
      shell: bash
    - id: spirv-llvm-sha
      run: scripts/get_sha.sh >> $GITHUB_OUTPUT
      env:
        URL: https://api.github.com/repos/CHIP-SPV/SPIRV-LLVM-Translator/git/ref/heads/chipStar-llvm-${{ inputs.llvm-version }}
        TOKEN: u:${{github.token}}
      shell: bash
    - id: pocl-sha
      run: scripts/get_sha.sh >> $GITHUB_OUTPUT
      env:
        URL: https://api.github.com/repos/pocl/pocl/git/refs/tags/v${{ inputs.pocl-version }}.0
        TOKEN: u:${{ github.token }}
      shell: bash
