// Stub header — redirects CUDA CUB includes to hipCUB equivalents.
// Generated by chipStar for rocThrust CUDA compatibility layer.
#ifndef CHIPSTAR_STUB_CUB_DEVICE_DEVICE_RADIX_SORT_CUH
#define CHIPSTAR_STUB_CUB_DEVICE_DEVICE_RADIX_SORT_CUH
// hipCUB provides the actual implementation via rocPRIM.
// This stub exists so that CUDA Thrust compatibility headers
// (installed by rocThrust) can be included without errors.
#endif
