#ifndef HIP_INCLUDE_DEVICELIB_TYPE_CASTING_INTRINSICS_H
#define HIP_INCLUDE_DEVICELIB_TYPE_CASTING_INTRINSICS_H

#include <hip/devicelib/macros.hh>

// __device__ float __double2float_rd ( double  x )
// __device__ float __double2float_rn ( double  x )
// __device__ float __double2float_ru ( double  x )
// __device__ float __double2float_rz ( double  x )
// __device__ int __double2hiint ( double  x )
// __device__ int __double2int_rd ( double  x )
// __device__ int __double2int_rn ( double  x )
// __device__ int __double2int_ru ( double  x )
// __device__ int __double2int_rz ( double  x )
// __device__ long long int 	__double2ll_rd ( double  x )
// __device__ long long int 	__double2ll_rn ( double  x )
// __device__ long long int 	__double2ll_ru ( double  x )
// __device__ long long int 	__double2ll_rz ( double  x )
// __device__ int __double2loint ( double  x )
// __device__ unsigned int 	__double2uint_rd ( double  x )
// __device__ unsigned int 	__double2uint_rn ( double  x )
// __device__ unsigned int 	__double2uint_ru ( double  x )
// __device__ unsigned int 	__double2uint_rz ( double  x )
// __device__ unsigned long long int 	__double2ull_rd ( double  x )
// __device__ unsigned long long int 	__double2ull_rn ( double  x )
// __device__ unsigned long long int 	__double2ull_ru ( double  x )
// __device__ unsigned long long int 	__double2ull_rz ( double  x )
// __device__ long long int 	__double_as_longlong ( double  x )
// __device__ int __float2int_rd ( float  x )
// __device__ int __float2int_rn ( float  x )
// __device__ int __float2int_ru ( float )
// __device__ int __float2int_rz ( float  x )
// __device__ long long int 	__float2ll_rd ( float  x )
// __device__ long long int 	__float2ll_rn ( float  x )
// __device__ long long int 	__float2ll_ru ( float  x )
// __device__ long long int 	__float2ll_rz ( float  x )
// __device__ unsigned int 	__float2uint_rd ( float  x )
// __device__ unsigned int 	__float2uint_rn ( float  x )
// __device__ unsigned int 	__float2uint_ru ( float  x )
// __device__ unsigned int 	__float2uint_rz ( float  x )
// __device__ unsigned long long int 	__float2ull_rd ( float  x )
// __device__ unsigned long long int 	__float2ull_rn ( float  x )
// __device__ unsigned long long int 	__float2ull_ru ( float  x )
// __device__ unsigned long long int 	__float2ull_rz ( float  x )
// __device__ int __float_as_int ( float  x )
// __device__ unsigned int 	__float_as_uint ( float  x )
// __device__ double __hiloint2double ( int  hi, int  lo )
// __device__ double __int2double_rn ( int  x )
// __device__ float __int2float_rd ( int  x )
// __device__ float __int2float_rn ( int  x )
// __device__ float __int2float_ru ( int  x )
// __device__ float __int2float_rz ( int  x )
// __device__ float __int_as_float ( int  x )
// __device__ double __ll2double_rd ( long long int x )
// __device__ double __ll2double_rn ( long long int x )
// __device__ double __ll2double_ru ( long long int x )
// __device__ double __ll2double_rz ( long long int x )
// __device__ float __ll2float_rd ( long long int x )
// __device__ float __ll2float_rn ( long long int x )
// __device__ float __ll2float_ru ( long long int x )
// __device__ float __ll2float_rz ( long long int x )
// __device__ double __longlong_as_double ( long long int x )
// __device__ double __uint2double_rn ( unsigned int  x )
// __device__ float __uint2float_rd ( unsigned int  x )
// __device__ float __uint2float_rn ( unsigned int  x )
// __device__ float __uint2float_ru ( unsigned int  x )
// __device__ float __uint2float_rz ( unsigned int  x )
// __device__ float __uint_as_float ( unsigned int  x )
// __device__ double __ull2double_rd ( unsigned long long int x )
// __device__ double __ull2double_rn ( unsigned long long int x )
// __device__ double __ull2double_ru ( unsigned long long int x )
// __device__ double __ull2double_rz ( unsigned long long int x )
// __device__ float __ull2float_rd ( unsigned long long int x )
// __device__ float __ull2float_rn ( unsigned long long int x )
// __device__ float __ull2float_ru ( unsigned long long int x )
// __device__ float __ull2float_rz ( unsigned long long int x )

#endif // include guard