# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: unit-test-checker

on:
  pull_request:
    paths-ignore: "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# pocl-cpu
# opencl-igpu
# opencl-dgpu
# opencl-cpu
# levelzero-igpu
# levelzero-dgpu

jobs:
    build-llvm-15-debug:
        runs-on: dgpu
        steps:
          - uses: actions/checkout@v2
            with:
              ref: ${{ github.event.pull_request.head.sha }}
              fetch-depth: 0
          - name: Compile llvm-15 debug
            run: ./scripts/compile.sh debug llvm-15
            shell: bash
      unit-tests-llvm-15-debug-pocl-cpu:
        needs: build-llvm-15-debug
        runs-on: dgpu
        steps:
          - name: Run unit test checking script
            run: ./scripts/unit_tests.sh debug llvm-15 pocl-cpu
            shell: bash

        
# jobs:
#   unit-tests-llvm-15-debug:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
#           fetch-depth: 0
#       - name: Run unit test checking script
#         run: ./scripts/unit_tests.sh debug llvm-15
#         shell: bash
#   unit-tests-llvm-15-release:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
#           fetch-depth: 0
#       - name: Run unit test checking script
#         run: ./scripts/unit_tests.sh release llvm-15
#         shell: bash
#   unit-tests-llvm-16-debug:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
#           fetch-depth: 0
#       - name: Run unit test checking script
#         run: ./scripts/unit_tests.sh debug llvm-16
#         shell: bash
#   unit-tests-llvm-16-release:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
#           fetch-depth: 0
#       - name: Run unit test checking script
#         run: ./scripts/unit_tests.sh release llvm-16
#         shell: bash