# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: unit-test-checker

on:
  pull_request:
    paths-ignore: "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests-llvm-15-debug:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh debug llvm-15
        shell: bash
  unit-tests-llvm-15-release:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh release llvm-15
        shell: bash
  unit-tests-llvm-16-debug:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh debug llvm-16
        shell: bash
  unit-tests-llvm-16-release:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh release llvm-16
        shell: bash
  unit-tests-llvm-17-debug:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh debug llvm-17
        shell: bash
  unit-tests-llvm-17-release:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh release llvm-17
        shell: bash
  unit-tests-llvm-18-debug:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh debug llvm-18
        shell: bash
  unit-tests-llvm-18-release:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/unit_tests.sh release llvm-18
        shell: bash