# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:
    paths-ignore: "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests-llvm-18-release-salami:
    runs-on: [self-hosted, Linux, ARM64]
    env:
      CHIP_MODULE_CACHE_DIR: ""
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: 'recursive'
      - name: Run unit test checking script
        run:  ./scripts/unit_tests.sh release llvm-18
        shell: bash
