# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: unit-test-checker

on:
  pull_request:
    paths-ignore: "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-checker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./.github/scripts/check_unit_tests.sh
        shell: bash

      # Failing tests tend to crash the driver to better just to run them manually
      # - name: Check for resolved tests
      #   run: .github/scripts/check_for_resolved_tests.py ./build
      #   shell: bash

