# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: check-for-resolved-tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-checker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run unit test checking script
        run: ./scripts/all_check_for_resolved_tests.sh
        shell: bash
