name: Nightly Tests Intel GPUs

on:
  schedule:
    - cron: '* * * * *' 
  workflow_dispatch:  # Allows manual triggering

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  unit-tests-llvm-19-release:
    runs-on: [self-hosted, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Restore nightly cache
        uses: actions/cache@v3
        with:
          path: |
            build
            ~/.cache/ccache
          key: nightly-build-${{ github.sha }}
          restore-keys: |
            nightly-build-

      - name: Run Intel GPU Unit Tests
        shell: bash
        run: |
          ./scripts/unit_tests.sh release llvm-19 --skip-build
